apiVersion: v1
kind: Pod
metadata:
  name: devops-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values: 
            - ssd
  containers:
  - image: nginx
    name: nginx-pod

