kind: Pod
apiVersion: v1
metadata:
  name: nginx-web
spec:
  volumes:
  - name: dhondu-volume
    persistentVolumeClaim: 
      claimName: devops-pvc
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: dhondu-volume


  