kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops-pvc
spec:
  # selector:
  #   matchLabels: 
  #     papa: dondhu
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 5Gi
  storageClassName: devops-sc
  