apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netflix
  name: netflix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - image: devopsinsiders/netflix-clone
        name: netflix
        ports:
        - containerPort: 80