apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: netflix.pawankumar.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflix-svc
            port:
              number: 80