apiVersion: v1
kind: LimitRange
metadata:
  name: devopslimit
  namespace: devops
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 200Mi
    min:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: 200m
      memory: 400Mi